const Food = require('../models/Food');

const FOODS = [
  // ─── FRUITS ──────────────────────────────────────────────
  { name:'Banana', nameAlt:['kela'], category:'fruit', cuisineType:'common', servingSize:120, servingUnit:'g', servingLabel:'1 medium (120g)', calories:107, protein:1.3, carbs:27, fat:0.4, fiber:3.1, sugar:14, sodium:1, tags:['vegan','vegetarian','high-carb'], mealTypes:['breakfast','snack'], emoji:'🍌' },
  { name:'Apple', nameAlt:['seb'], category:'fruit', cuisineType:'common', servingSize:182, servingUnit:'g', servingLabel:'1 medium (182g)', calories:95, protein:0.5, carbs:25, fat:0.3, fiber:4.4, sugar:19, sodium:2, tags:['vegan','vegetarian','low-fat'], mealTypes:['breakfast','snack'], emoji:'🍎' },
  { name:'Mango', nameAlt:['aam'], category:'fruit', cuisineType:'common', servingSize:165, servingUnit:'g', servingLabel:'1 cup sliced (165g)', calories:99, protein:1.4, carbs:25, fat:0.6, fiber:2.6, sugar:22, sodium:2, tags:['vegan','vegetarian'], mealTypes:['breakfast','snack'], emoji:'🥭' },
  { name:'Orange', nameAlt:['santra','narangi'], category:'fruit', cuisineType:'common', servingSize:131, servingUnit:'g', servingLabel:'1 medium (131g)', calories:62, protein:1.2, carbs:15, fat:0.2, fiber:3.1, sugar:12, sodium:0, tags:['vegan','vegetarian','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🍊' },
  { name:'Grapes', nameAlt:['angoor'], category:'fruit', cuisineType:'common', servingSize:150, servingUnit:'g', servingLabel:'1 cup (150g)', calories:104, protein:1.1, carbs:27, fat:0.2, fiber:1.4, sugar:23, sodium:3, tags:['vegan','vegetarian'], mealTypes:['snack'], emoji:'🍇' },
  { name:'Watermelon', nameAlt:['tarbooz'], category:'fruit', cuisineType:'common', servingSize:280, servingUnit:'g', servingLabel:'2 cups (280g)', calories:85, protein:1.7, carbs:21, fat:0.4, fiber:1.1, sugar:17, sodium:3, tags:['vegan','vegetarian','low-calorie','hydrating'], mealTypes:['snack'], emoji:'🍉' },
  { name:'Papaya', nameAlt:['papita'], category:'fruit', cuisineType:'common', servingSize:145, servingUnit:'g', servingLabel:'1 cup (145g)', calories:62, protein:0.7, carbs:16, fat:0.4, fiber:2.5, sugar:11, sodium:12, tags:['vegan','vegetarian','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🍈' },
  { name:'Guava', nameAlt:['amrood'], category:'fruit', cuisineType:'common', servingSize:165, servingUnit:'g', servingLabel:'1 cup (165g)', calories:112, protein:4.2, carbs:24, fat:1.6, fiber:8.9, sugar:15, sodium:3, tags:['vegan','vegetarian','high-fiber'], mealTypes:['snack'], emoji:'🍐' },
  { name:'Pomegranate', nameAlt:['anaar'], category:'fruit', cuisineType:'common', servingSize:174, servingUnit:'g', servingLabel:'1 cup (174g)', calories:144, protein:2.9, carbs:33, fat:2.1, fiber:7, sugar:24, sodium:5, tags:['vegan','vegetarian'], mealTypes:['snack'], emoji:'🔴' },
  { name:'Pineapple', nameAlt:['ananas'], category:'fruit', cuisineType:'common', servingSize:165, servingUnit:'g', servingLabel:'1 cup (165g)', calories:82, protein:0.9, carbs:22, fat:0.2, fiber:2.3, sugar:16, sodium:2, tags:['vegan','vegetarian'], mealTypes:['breakfast','snack'], emoji:'🍍' },

  // ─── VEGETABLES ──────────────────────────────────────────
  { name:'Carrot', nameAlt:['gajar'], category:'vegetable', cuisineType:'common', servingSize:128, servingUnit:'g', servingLabel:'1 cup chopped (128g)', calories:52, protein:1.2, carbs:12, fat:0.3, fiber:3.6, sugar:6, sodium:88, tags:['vegan','vegetarian','low-calorie','high-fiber'], mealTypes:['lunch','dinner','snack'], emoji:'🥕' },
  { name:'Broccoli', category:'vegetable', cuisineType:'international', servingSize:91, servingUnit:'g', servingLabel:'1 cup (91g)', calories:31, protein:2.6, carbs:6, fat:0.3, fiber:2.4, sugar:1.5, sodium:30, tags:['vegan','vegetarian','low-calorie','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🥦' },
  { name:'Spinach', nameAlt:['palak'], category:'vegetable', cuisineType:'common', servingSize:30, servingUnit:'g', servingLabel:'1 cup raw (30g)', calories:7, protein:0.9, carbs:1.1, fat:0.1, fiber:0.7, sugar:0.1, sodium:24, tags:['vegan','vegetarian','low-calorie','iron-rich'], mealTypes:['lunch','dinner'], emoji:'🥬' },
  { name:'Potato', nameAlt:['aloo'], category:'vegetable', cuisineType:'common', servingSize:150, servingUnit:'g', servingLabel:'1 medium (150g)', calories:130, protein:3, carbs:30, fat:0.2, fiber:2.4, sugar:1.3, sodium:10, tags:['vegan','vegetarian'], mealTypes:['breakfast','lunch','dinner'], emoji:'🥔' },
  { name:'Tomato', nameAlt:['tamatar'], category:'vegetable', cuisineType:'common', servingSize:123, servingUnit:'g', servingLabel:'1 medium (123g)', calories:22, protein:1.1, carbs:4.8, fat:0.2, fiber:1.5, sugar:3.2, sodium:6, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🍅' },
  { name:'Onion', nameAlt:['pyaz'], category:'vegetable', cuisineType:'common', servingSize:110, servingUnit:'g', servingLabel:'1 medium (110g)', calories:44, protein:1.2, carbs:10, fat:0.1, fiber:1.9, sugar:4.7, sodium:5, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🧅' },
  { name:'Cauliflower', nameAlt:['phool gobhi'], category:'vegetable', cuisineType:'common', servingSize:100, servingUnit:'g', servingLabel:'1 cup (100g)', calories:25, protein:2, carbs:5, fat:0.3, fiber:2, sugar:1.9, sodium:30, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🥦' },
  { name:'Cabbage', nameAlt:['patta gobhi'], category:'vegetable', cuisineType:'common', servingSize:89, servingUnit:'g', servingLabel:'1 cup chopped (89g)', calories:22, protein:1.1, carbs:5.2, fat:0.1, fiber:2.2, sugar:2.9, sodium:16, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🥬' },
  { name:'Okra', nameAlt:['bhindi','ladyfinger'], category:'vegetable', cuisineType:'common', servingSize:100, servingUnit:'g', servingLabel:'1 cup (100g)', calories:33, protein:1.9, carbs:7, fat:0.2, fiber:3.2, sugar:1.5, sodium:7, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🥒' },
  { name:'Eggplant', nameAlt:['baingan','brinjal'], category:'vegetable', cuisineType:'common', servingSize:100, servingUnit:'g', servingLabel:'1 cup (100g)', calories:25, protein:1, carbs:6, fat:0.2, fiber:3, sugar:3.5, sodium:2, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🍆' },

  // ─── SOUTH INDIAN ────────────────────────────────────────
  { name:'Idli', category:'south_indian', cuisineType:'south_indian', servingSize:120, servingUnit:'g', servingLabel:'2 pieces (120g)', calories:148, protein:4.8, carbs:30, fat:0.6, fiber:1.2, sugar:0.5, sodium:320, tags:['vegetarian','low-fat','fermented'], mealTypes:['breakfast','snack'], emoji:'🫓' },
  { name:'Plain Dosa', nameAlt:['dosa'], category:'south_indian', cuisineType:'south_indian', servingSize:100, servingUnit:'g', servingLabel:'1 dosa (100g)', calories:168, protein:4, carbs:35, fat:1.5, fiber:1.5, sugar:0.8, sodium:300, tags:['vegetarian','fermented'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Masala Dosa', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 dosa (200g)', calories:340, protein:7, carbs:56, fat:9, fiber:3, sugar:2, sodium:520, tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Sambar', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'ml', servingLabel:'1 cup (200ml)', calories:102, protein:5.2, carbs:16, fat:2.4, fiber:4, sugar:3, sodium:480, tags:['vegan','vegetarian','high-fiber'], mealTypes:['breakfast','lunch','dinner'], emoji:'🍲' },
  { name:'Pongal', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:280, protein:7, carbs:48, fat:7, fiber:2, sugar:1, sodium:350, tags:['vegetarian'], mealTypes:['breakfast'], emoji:'🍚' },
  { name:'Uttapam', category:'south_indian', cuisineType:'south_indian', servingSize:150, servingUnit:'g', servingLabel:'1 piece (150g)', calories:218, protein:6, carbs:38, fat:4, fiber:2, sugar:2, sodium:380, tags:['vegetarian'], mealTypes:['breakfast','snack'], emoji:'🥞' },
  { name:'Curd Rice', nameAlt:['thayir sadam'], category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:240, protein:7, carbs:44, fat:3.5, fiber:0.5, sugar:3, sodium:280, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Rasam', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'ml', servingLabel:'1 cup (200ml)', calories:55, protein:1.5, carbs:10, fat:1, fiber:1.2, sugar:1.5, sodium:440, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🍵' },
  { name:'Vada', nameAlt:['medu vada'], category:'south_indian', cuisineType:'south_indian', servingSize:80, servingUnit:'g', servingLabel:'1 piece (80g)', calories:230, protein:6, carbs:28, fat:10, fiber:3, sugar:1, sodium:400, tags:['vegetarian','fried'], mealTypes:['breakfast','snack'], emoji:'🍩' },
  { name:'Bisi Bele Bath', category:'south_indian', cuisineType:'south_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:380, protein:10, carbs:55, fat:12, fiber:6, sugar:4, sodium:550, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Lemon Rice', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:280, protein:5, carbs:48, fat:7, fiber:2, sugar:0, sodium:300, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Appam', category:'south_indian', cuisineType:'south_indian', servingSize:100, servingUnit:'g', servingLabel:'1 piece (100g)', calories:120, protein:2, carbs:25, fat:1, fiber:1, sugar:1, sodium:150, tags:['vegan','vegetarian'], mealTypes:['breakfast','dinner'], emoji:'🥞' },
  { name:'Puttu', category:'south_indian', cuisineType:'south_indian', servingSize:150, servingUnit:'g', servingLabel:'1 piece (150g)', calories:200, protein:4, carbs:40, fat:2, fiber:3, sugar:2, sodium:10, tags:['vegan','vegetarian'], mealTypes:['breakfast'], emoji:'🫔' },

  // ─── NORTH INDIAN ────────────────────────────────────────
  { name:'Roti / Chapati', nameAlt:['chapati','roti','phulka'], category:'north_indian', cuisineType:'north_indian', servingSize:40, servingUnit:'g', servingLabel:'1 roti (40g)', calories:104, protein:3.5, carbs:19, fat:2, fiber:2.5, sugar:0.4, sodium:130, tags:['vegetarian','whole-wheat'], mealTypes:['breakfast','lunch','dinner'], emoji:'🫓' },
  { name:'Naan', category:'north_indian', cuisineType:'north_indian', servingSize:90, servingUnit:'g', servingLabel:'1 piece (90g)', calories:262, protein:8.5, carbs:45, fat:5.5, fiber:1.8, sugar:3, sodium:520, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🫓' },
  { name:'Paratha', nameAlt:['stuffed paratha'], category:'north_indian', cuisineType:'north_indian', servingSize:100, servingUnit:'g', servingLabel:'1 paratha (100g)', calories:300, protein:6, carbs:42, fat:11, fiber:3, sugar:1, sodium:450, tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🥙' },
  { name:'Aloo Paratha', category:'north_indian', cuisineType:'north_indian', servingSize:150, servingUnit:'g', servingLabel:'1 paratha (150g)', calories:350, protein:7, carbs:48, fat:14, fiber:4, sugar:2, sodium:600, tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🥙' },
  { name:'Paneer Butter Masala', nameAlt:['paneer makhani'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:430, protein:20, carbs:18, fat:32, fiber:3, sugar:8, sodium:680, tags:['vegetarian','high-protein','high-fat'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Dal Makhani', nameAlt:['dal makhni'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:310, protein:14, carbs:38, fat:10, fiber:9, sugar:4, sodium:580, tags:['vegetarian','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Rajma', nameAlt:['kidney beans curry'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:290, protein:16, carbs:44, fat:5, fiber:12, sugar:3, sodium:480, tags:['vegan','vegetarian','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Chole Bhature', nameAlt:['chhole bhature'], category:'north_indian', cuisineType:'north_indian', servingSize:300, servingUnit:'g', servingLabel:'1 plate (300g)', calories:580, protein:16, carbs:78, fat:22, fiber:10, sugar:5, sodium:820, tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🍽️' },
  { name:'Palak Paneer', category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:320, protein:18, carbs:12, fat:24, fiber:5, sugar:3, sodium:550, tags:['vegetarian','iron-rich'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Butter Chicken', nameAlt:['murgh makhani'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:450, protein:30, carbs:15, fat:30, fiber:2, sugar:5, sodium:800, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Aloo Gobi', category:'north_indian', cuisineType:'north_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:180, protein:4, carbs:22, fat:9, fiber:6, sugar:4, sodium:400, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Bhindi Masala', nameAlt:['okra curry'], category:'north_indian', cuisineType:'north_indian', servingSize:150, servingUnit:'g', servingLabel:'1 serving (150g)', calories:160, protein:3, carbs:12, fat:12, fiber:5, sugar:3, sodium:350, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍲' },

  // ─── WESTERN & CENTRAL INDIAN (MAHARASHTRIAN/GUJARATI/RAJASTHANI)
  { name:'Poha', category:'indian_common', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 plate (200g)', calories:250, protein:4.5, carbs:50, fat:4, fiber:2, sugar:2, sodium:320, tags:['vegetarian','vegan'], mealTypes:['breakfast','snack'], emoji:'🍽️' },
  { name:'Vada Pav', category:'snack', cuisineType:'maharashtrian', servingSize:150, servingUnit:'g', servingLabel:'1 piece (150g)', calories:300, protein:6, carbs:40, fat:13, fiber:3, sugar:2, sodium:550, tags:['vegetarian','street-food'], mealTypes:['snack'], emoji:'🍔' },
  { name:'Pav Bhaji', category:'north_indian', cuisineType:'maharashtrian', servingSize:250, servingUnit:'g', servingLabel:'1 plate (250g)', calories:400, protein:8, carbs:55, fat:16, fiber:8, sugar:5, sodium:800, tags:['vegetarian','street-food'], mealTypes:['lunch','dinner','snack'], emoji:'🍽️' },
  { name:'Dhokla', category:'snack', cuisineType:'gujarati', servingSize:100, servingUnit:'g', servingLabel:'2 pieces (100g)', calories:160, protein:6, carbs:28, fat:3, fiber:2, sugar:4, sodium:450, tags:['vegetarian','steamed'], mealTypes:['breakfast','snack'], emoji:'🧽' },
  { name:'Thepla', category:'indian_common', cuisineType:'gujarati', servingSize:50, servingUnit:'g', servingLabel:'1 piece (50g)', calories:150, protein:4, carbs:20, fat:6, fiber:3, sugar:1, sodium:200, tags:['vegetarian'], mealTypes:['breakfast','lunch','snack'], emoji:'🫓' },
  { name:'Misal Pav', category:'snack', cuisineType:'maharashtrian', servingSize:300, servingUnit:'g', servingLabel:'1 plate (300g)', calories:450, protein:15, carbs:60, fat:18, fiber:10, sugar:5, sodium:900, tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🍲' },
  { name:'Dal Bati Churma', category:'north_indian', cuisineType:'rajasthani', servingSize:350, servingUnit:'g', servingLabel:'1 plate (350g)', calories:650, protein:18, carbs:80, fat:28, fiber:12, sugar:10, sodium:600, tags:['vegetarian','high-calorie'], mealTypes:['lunch','dinner'], emoji:'🍽️' },

  // ─── EAST INDIAN (BENGALI/ODIA) ─────────────────────────
  { name:'Luchi', category:'north_indian', cuisineType:'bengali', servingSize:30, servingUnit:'g', servingLabel:'1 piece (30g)', calories:120, protein:2, carbs:14, fat:6, fiber:0.5, sugar:0, sodium:100, tags:['vegetarian','fried'], mealTypes:['breakfast','snack'], emoji:'🫓' },
  { name:'Fish Curry (Machher Jhol)', category:'indian_common', cuisineType:'bengali', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:320, protein:25, carbs:10, fat:20, fiber:1, sugar:2, sodium:550, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Pakhala Bhata', category:'indian_common', cuisineType:'odia', servingSize:300, servingUnit:'g', servingLabel:'1 bowl (300g)', calories:220, protein:5, carbs:45, fat:1, fiber:2, sugar:0, sodium:50, tags:['vegetarian','fermented'], mealTypes:['lunch'], emoji:'🍚' },

  // ─── INDIAN COMMON / GRAINS & PROTEINS ───────────────────
  { name:'Steamed Rice', nameAlt:['white rice','boiled rice','chawal'], category:'indian_common', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 cup cooked (200g)', calories:258, protein:5.3, carbs:56, fat:0.5, fiber:0.6, sugar:0, sodium:4, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Ghee', category:'indian_common', cuisineType:'common', servingSize:15, servingUnit:'g', servingLabel:'1 tbsp (15g)', calories:135, protein:0, carbs:0, fat:15, fiber:0, sugar:0, sodium:0, tags:['vegetarian','high-fat'], mealTypes:['breakfast','lunch','dinner'], emoji:'🧈' },
  { name:'Curd / Yogurt', nameAlt:['dahi','yogurt'], category:'dairy', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 cup (200g)', calories:118, protein:8, carbs:9, fat:4.6, fiber:0, sugar:7, sodium:115, tags:['vegetarian','probiotic','calcium-rich'], mealTypes:['breakfast','lunch','dinner','snack'], emoji:'🥛' },
  { name:'Milk', nameAlt:['dudh'], category:'dairy', cuisineType:'common', servingSize:240, servingUnit:'ml', servingLabel:'1 glass (240ml)', calories:149, protein:8, carbs:12, fat:8, fiber:0, sugar:12, sodium:105, tags:['vegetarian','calcium-rich'], mealTypes:['breakfast','snack'], emoji:'🥛' },
  { name:'Egg (Boiled)', nameAlt:['anda','egg'], category:'protein', cuisineType:'common', servingSize:50, servingUnit:'g', servingLabel:'1 large (50g)', calories:78, protein:6.3, carbs:0.6, fat:5.3, fiber:0, sugar:0.6, sodium:62, tags:['high-protein','low-carb'], mealTypes:['breakfast','snack'], emoji:'🥚' },
  { name:'Omelette', category:'protein', cuisineType:'common', servingSize:100, servingUnit:'g', servingLabel:'2 eggs (100g)', calories:190, protein:13, carbs:2, fat:14, fiber:0.5, sugar:1, sodium:250, tags:['non-veg','high-protein'], mealTypes:['breakfast','snack'], emoji:'🍳' },
  { name:'Egg Curry', category:'indian_common', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:250, protein:14, carbs:12, fat:16, fiber:3, sugar:3, sodium:500, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Chicken Curry', nameAlt:['murgh curry'], category:'indian_common', cuisineType:'common', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:395, protein:32, carbs:12, fat:24, fiber:2, sugar:4, sodium:690, tags:['high-protein','non-veg'], mealTypes:['lunch','dinner'], emoji:'🍗' },
  { name:'Biryani (Chicken)', nameAlt:['chicken biryani'], category:'indian_common', cuisineType:'common', servingSize:350, servingUnit:'g', servingLabel:'1 plate (350g)', calories:520, protein:28, carbs:68, fat:16, fiber:3, sugar:4, sodium:780, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Biryani (Mutton)', nameAlt:['mutton biryani'], category:'indian_common', cuisineType:'common', servingSize:350, servingUnit:'g', servingLabel:'1 plate (350g)', calories:650, protein:32, carbs:65, fat:28, fiber:3, sugar:4, sodium:850, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Biryani (Veg)', nameAlt:['veg biryani','pulao'], category:'indian_common', cuisineType:'common', servingSize:300, servingUnit:'g', servingLabel:'1 plate (300g)', calories:400, protein:8, carbs:70, fat:10, fiber:6, sugar:3, sodium:500, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Upma', category:'indian_common', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:202, protein:5, carbs:36, fat:5, fiber:2.5, sugar:1, sodium:360, tags:['vegetarian','vegan'], mealTypes:['breakfast','snack'], emoji:'🍽️' },
  { name:'Khichdi', category:'indian_common', cuisineType:'common', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:280, protein:9, carbs:48, fat:6, fiber:5, sugar:2, sodium:350, tags:['vegetarian','comfort-food'], mealTypes:['lunch','dinner'], emoji:'🍲' },

  // ─── GYM / PROTEIN FOODS ─────────────────────────────────
  { name:'Chicken Breast (Grilled)', nameAlt:['grilled chicken'], category:'gym', cuisineType:'international', servingSize:150, servingUnit:'g', servingLabel:'1 fillet (150g)', calories:247, protein:46, carbs:0, fat:5.3, fiber:0, sugar:0, sodium:129, tags:['high-protein','low-carb','low-fat','non-veg'], mealTypes:['lunch','dinner'], emoji:'🍗' },
  { name:'Whey Protein Shake', nameAlt:['protein shake','whey'], category:'gym', cuisineType:'international', servingSize:30, servingUnit:'g', servingLabel:'1 scoop (30g)', calories:120, protein:24, carbs:3, fat:1.5, fiber:0, sugar:2, sodium:130, tags:['high-protein','low-carb','gym'], mealTypes:['breakfast','snack'], emoji:'💪' },
  { name:'Oats', nameAlt:['oatmeal','rolled oats'], category:'grain', cuisineType:'international', servingSize:80, servingUnit:'g', servingLabel:'1 cup dry (80g)', calories:296, protein:10, carbs:53, fat:5.2, fiber:8, sugar:1, sodium:5, tags:['vegan','vegetarian','high-fiber','gym'], mealTypes:['breakfast'], emoji:'🥣' },
  { name:'Brown Rice', category:'grain', cuisineType:'international', servingSize:195, servingUnit:'g', servingLabel:'1 cup cooked (195g)', calories:216, protein:5, carbs:45, fat:1.8, fiber:3.5, sugar:0.7, sodium:10, tags:['vegan','vegetarian','high-fiber','gym'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Greek Yogurt', nameAlt:['greek curd'], category:'dairy', cuisineType:'international', servingSize:200, servingUnit:'g', servingLabel:'1 cup (200g)', calories:130, protein:17, carbs:7, fat:3.5, fiber:0, sugar:6, sodium:95, tags:['vegetarian','high-protein','gym','probiotic'], mealTypes:['breakfast','snack'], emoji:'🥛' },
  { name:'Almonds', nameAlt:['badam'], category:'snack', cuisineType:'common', servingSize:28, servingUnit:'g', servingLabel:'1 oz / ~23 nuts (28g)', calories:164, protein:6, carbs:6, fat:14, fiber:3.5, sugar:1.2, sodium:1, tags:['vegan','vegetarian','high-fat','gym','keto-friendly'], mealTypes:['snack'], emoji:'🌰' },
  { name:'Walnuts', nameAlt:['akhrot'], category:'snack', cuisineType:'common', servingSize:28, servingUnit:'g', servingLabel:'1 oz (28g)', calories:185, protein:4.3, carbs:3.9, fat:18.5, fiber:1.9, sugar:0.7, sodium:1, tags:['vegan','vegetarian','high-fat','omega-3'], mealTypes:['snack'], emoji:'🌰' },
  { name:'Peanuts (Roasted)', nameAlt:['moongfali'], category:'snack', cuisineType:'common', servingSize:30, servingUnit:'g', servingLabel:'1 handful (30g)', calories:170, protein:7, carbs:6, fat:14, fiber:2.5, sugar:1, sodium:5, tags:['vegan','vegetarian','high-protein'], mealTypes:['snack'], emoji:'🥜' },
  { name:'Peanut Butter', nameAlt:['peanut butter','moongfali butter'], category:'gym', cuisineType:'international', servingSize:32, servingUnit:'g', servingLabel:'2 tbsp (32g)', calories:188, protein:8, carbs:7, fat:16, fiber:1.9, sugar:3, sodium:152, tags:['vegetarian','high-protein','high-fat','gym'], mealTypes:['breakfast','snack'], emoji:'🥜' },
  { name:'Quinoa', category:'grain', cuisineType:'international', servingSize:185, servingUnit:'g', servingLabel:'1 cup cooked (185g)', calories:222, protein:8, carbs:39, fat:3.5, fiber:5, sugar:1.6, sodium:13, tags:['vegan','vegetarian','high-protein','gym','gluten-free'], mealTypes:['lunch','dinner'], emoji:'🌾' },
  { name:'Tuna (Canned)', nameAlt:['canned tuna'], category:'gym', cuisineType:'international', servingSize:100, servingUnit:'g', servingLabel:'1 small can (100g)', calories:116, protein:25, carbs:0, fat:1, fiber:0, sugar:0, sodium:333, tags:['high-protein','low-carb','low-fat','non-veg','gym'], mealTypes:['lunch','dinner'], emoji:'🐟' },
  { name:'Soya Chunks', nameAlt:['meal maker','soya'], category:'gym', cuisineType:'indian_common', servingSize:50, servingUnit:'g', servingLabel:'50g raw', calories:172, protein:26, carbs:16, fat:0.5, fiber:6, sugar:0, sodium:10, tags:['vegan','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },

  // ─── SNACKS & STREET FOOD ──────────────────────────────────
  { name:'Samosa', category:'snack', cuisineType:'north_indian', servingSize:100, servingUnit:'g', servingLabel:'1 piece (100g)', calories:262, protein:5, carbs:30, fat:14, fiber:2.5, sugar:2, sodium:420, tags:['vegetarian'], mealTypes:['snack'], emoji:'🥟' },
  { name:'Kachori', category:'snack', cuisineType:'north_indian', servingSize:80, servingUnit:'g', servingLabel:'1 piece (80g)', calories:250, protein:4, carbs:28, fat:13, fiber:2, sugar:1, sodium:350, tags:['vegetarian','fried'], mealTypes:['snack'], emoji:'🥟' },
  { name:'Pani Puri / Golgappa', category:'snack', cuisineType:'indian_common', servingSize:150, servingUnit:'g', servingLabel:'6 pieces (150g)', calories:200, protein:4, carbs:35, fat:5, fiber:3, sugar:4, sodium:600, tags:['vegetarian','street-food'], mealTypes:['snack'], emoji:'🥣' },
  { name:'Bhel Puri', category:'snack', cuisineType:'maharashtrian', servingSize:150, servingUnit:'g', servingLabel:'1 plate (150g)', calories:280, protein:5, carbs:55, fat:5, fiber:4, sugar:8, sodium:750, tags:['vegetarian','vegan','street-food'], mealTypes:['snack'], emoji:'🥗' },
  { name:'Jalebi', category:'snack', cuisineType:'indian_common', servingSize:50, servingUnit:'g', servingLabel:'2 pieces (50g)', calories:150, protein:1, carbs:28, fat:4, fiber:0, sugar:20, sodium:5, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'🥨' },
  { name:'Gulab Jamun', category:'snack', cuisineType:'indian_common', servingSize:80, servingUnit:'g', servingLabel:'2 pieces (80g)', calories:300, protein:4, carbs:42, fat:13, fiber:0, sugar:30, sodium:40, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'🍩' },
  { name:'Rasgulla', category:'snack', cuisineType:'bengali', servingSize:100, servingUnit:'g', servingLabel:'2 pieces (100g)', calories:186, protein:3, carbs:40, fat:1.5, fiber:0, sugar:35, sodium:10, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'⚪' },
  { name:'Pakora / Bhajiya', category:'snack', cuisineType:'indian_common', servingSize:100, servingUnit:'g', servingLabel:'1 serving (100g)', calories:250, protein:6, carbs:25, fat:15, fiber:4, sugar:1, sodium:400, tags:['vegetarian','fried'], mealTypes:['snack'], emoji:'🧆' },
  
  // ─── BEVERAGES ───────────────────────────────────────────
  { name:'Black Coffee', nameAlt:['coffee','black coffee'], category:'beverage', cuisineType:'international', servingSize:240, servingUnit:'ml', servingLabel:'1 cup (240ml)', calories:5, protein:0.3, carbs:0, fat:0, fiber:0, sugar:0, sodium:7, tags:['vegan','low-calorie','gym'], mealTypes:['breakfast','snack'], emoji:'☕' },
  { name:'Green Tea', nameAlt:['herbal tea'], category:'beverage', cuisineType:'international', servingSize:240, servingUnit:'ml', servingLabel:'1 cup (240ml)', calories:3, protein:0, carbs:0, fat:0, fiber:0, sugar:0, sodium:7, tags:['vegan','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🍵' },
  { name:'Masala Chai / Tea', nameAlt:['chai','tea'], category:'beverage', cuisineType:'indian_common', servingSize:150, servingUnit:'ml', servingLabel:'1 cup (150ml)', calories:90, protein:2, carbs:12, fat:3, fiber:0, sugar:10, sodium:30, tags:['vegetarian'], mealTypes:['breakfast','snack'], emoji:'☕' },
  { name:'Banana Milkshake', nameAlt:['milkshake','banana shake'], category:'beverage', cuisineType:'common', servingSize:300, servingUnit:'ml', servingLabel:'1 glass (300ml)', calories:260, protein:7, carbs:45, fat:6, fiber:2, sugar:36, sodium:100, tags:['vegetarian','gym'], mealTypes:['breakfast','snack'], emoji:'🥤' },
  { name:'Lassi (Sweet)', nameAlt:['lassi'], category:'beverage', cuisineType:'north_indian', servingSize:250, servingUnit:'ml', servingLabel:'1 glass (250ml)', calories:200, protein:7, carbs:25, fat:8, fiber:0, sugar:20, sodium:100, tags:['vegetarian'], mealTypes:['lunch','snack'], emoji:'🥛' },
  { name:'Buttermilk / Chaas', nameAlt:['majjiga','chaas'], category:'beverage', cuisineType:'indian_common', servingSize:250, servingUnit:'ml', servingLabel:'1 glass (250ml)', calories:60, protein:3, carbs:5, fat:2, fiber:0, sugar:4, sodium:300, tags:['vegetarian','low-calorie'], mealTypes:['lunch','snack'], emoji:'🥛' },
  { name:'Coconut Water', nameAlt:['nariyal pani'], category:'beverage', cuisineType:'indian_common', servingSize:250, servingUnit:'ml', servingLabel:'1 glass (250ml)', calories:45, protein:1.5, carbs:10, fat:0.5, fiber:0, sugar:6, sodium:250, tags:['vegan','hydrating','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🥥' },

  // ─── DAIRY & OTHERS ──────────────────────────────────────
  { name:'Paneer (Cottage Cheese)', nameAlt:['paneer','cottage cheese'], category:'dairy', cuisineType:'common', servingSize:100, servingUnit:'g', servingLabel:'100g', calories:265, protein:18, carbs:3, fat:20, fiber:0, sugar:2, sodium:120, tags:['vegetarian','high-protein','gym','keto-friendly'], mealTypes:['breakfast','lunch','dinner','snack'], emoji:'🧀' },
  { name:'Salmon (Grilled)', nameAlt:['salmon','fish'], category:'gym', cuisineType:'international', servingSize:150, servingUnit:'g', servingLabel:'1 fillet (150g)', calories:280, protein:39, carbs:0, fat:13, fiber:0, sugar:0, sodium:100, tags:['high-protein','low-carb','non-veg','gym','omega-3'], mealTypes:['lunch','dinner'], emoji:'🐟' },
  { name:'Mutton Curry', category:'indian_common', cuisineType:'common', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:450, protein:35, carbs:10, fat:28, fiber:2, sugar:2, sodium:700, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },

  // ─── MORE INDIAN REGIONAL ─────────────────────────────────
  { name:'Pesarattu', category:'south_indian', cuisineType:'andhra', servingSize:150, servingUnit:'g', servingLabel:'1 dosa (150g)', calories:220, protein:10, carbs:35, fat:5, fiber:6, sugar:2, sodium:350, tags:['vegetarian','high-protein'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Gongura Pachadi', category:'south_indian', cuisineType:'andhra', servingSize:30, servingUnit:'g', servingLabel:'2 tbsp (30g)', calories:50, protein:1, carbs:5, fat:3, fiber:2, sugar:0, sodium:400, tags:['vegan','vegetarian','spicy'], mealTypes:['lunch','dinner'], emoji:'🥣' },
  { name:'Hyderabadi Haleem', category:'indian_common', cuisineType:'hyderabadi', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:480, protein:30, carbs:45, fat:20, fiber:8, sugar:2, sodium:850, tags:['non-veg','high-protein'], mealTypes:['dinner'], emoji:'🍲' },
  { name:'Malabar Parotta', category:'south_indian', cuisineType:'kerala', servingSize:100, servingUnit:'g', servingLabel:'1 piece (100g)', calories:320, protein:6, carbs:40, fat:14, fiber:2, sugar:2, sodium:450, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🫓' },
  { name:'Kerala Beef Curry', category:'indian_common', cuisineType:'kerala', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:410, protein:32, carbs:10, fat:25, fiber:2, sugar:1, sodium:650, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Kashmiri Rogan Josh', category:'north_indian', cuisineType:'kashmiri', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:460, protein:34, carbs:8, fat:30, fiber:2, sugar:3, sodium:720, tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Makki di Roti', category:'north_indian', cuisineType:'punjabi', servingSize:50, servingUnit:'g', servingLabel:'1 roti (50g)', calories:140, protein:3, carbs:28, fat:2, fiber:3, sugar:1, sodium:100, tags:['vegan','vegetarian','gluten-free'], mealTypes:['lunch','dinner'], emoji:'🫓' },
  { name:'Sarson ka Saag', category:'north_indian', cuisineType:'punjabi', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:120, protein:6, carbs:12, fat:6, fiber:5, sugar:2, sodium:350, tags:['vegetarian','low-calorie','iron-rich'], mealTypes:['lunch','dinner'], emoji:'🥬' },
  { name:'Litti Chokha', category:'north_indian', cuisineType:'bihari', servingSize:200, servingUnit:'g', servingLabel:'2 pieces with chokha (200g)', calories:380, protein:12, carbs:65, fat:10, fiber:8, sugar:4, sodium:500, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🧆' },
  { name:'Puran Poli', category:'snack', cuisineType:'maharashtrian', servingSize:100, servingUnit:'g', servingLabel:'1 piece (100g)', calories:290, protein:6, carbs:55, fat:5, fiber:4, sugar:22, sodium:15, tags:['vegetarian','sweet'], mealTypes:['snack','dinner'], emoji:'🫓' },
  { name:'Modak', category:'snack', cuisineType:'maharashtrian', servingSize:50, servingUnit:'g', servingLabel:'2 pieces (50g)', calories:150, protein:2, carbs:25, fat:4, fiber:1, sugar:12, sodium:5, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'🥟' },
  { name:'Khandvi', category:'snack', cuisineType:'gujarati', servingSize:100, servingUnit:'g', servingLabel:'1 serving (100g)', calories:210, protein:8, carbs:25, fat:9, fiber:3, sugar:4, sodium:300, tags:['vegetarian','steamed'], mealTypes:['snack'], emoji:'🫔' },
  { name:'Undhiyu', category:'indian_common', cuisineType:'gujarati', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:280, protein:6, carbs:35, fat:12, fiber:8, sugar:5, sodium:400, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Momo (Veg)', category:'snack', cuisineType:'north_east', servingSize:150, servingUnit:'g', servingLabel:'6 pieces (150g)', calories:210, protein:5, carbs:38, fat:3, fiber:2, sugar:2, sodium:450, tags:['vegan','vegetarian','steamed'], mealTypes:['snack'], emoji:'🥟' },
  { name:'Momo (Chicken)', category:'snack', cuisineType:'north_east', servingSize:150, servingUnit:'g', servingLabel:'6 pieces (150g)', calories:240, protein:12, carbs:32, fat:6, fiber:1, sugar:1, sodium:550, tags:['non-veg','steamed'], mealTypes:['snack'], emoji:'🥟' },
  { name:'Thukpa', category:'indian_common', cuisineType:'north_east', servingSize:350, servingUnit:'g', servingLabel:'1 large bowl (350g)', calories:320, protein:15, carbs:50, fat:6, fiber:4, sugar:3, sodium:800, tags:['non-veg','comfort-food'], mealTypes:['lunch','dinner'], emoji:'🍜' },

  // ─── MORE FAST FOOD & INTERNATIONAL ───────────────────────
  { name:'Pizza (Margherita)', category:'snack', cuisineType:'international', servingSize:150, servingUnit:'g', servingLabel:'1 slice (150g)', calories:280, protein:12, carbs:36, fat:10, fiber:2, sugar:3, sodium:600, tags:['vegetarian'], mealTypes:['lunch','dinner','snack'], emoji:'🍕' },
  { name:'Burger (Veg)', category:'snack', cuisineType:'international', servingSize:200, servingUnit:'g', servingLabel:'1 burger (200g)', calories:350, protein:10, carbs:50, fat:12, fiber:5, sugar:6, sodium:750, tags:['vegetarian'], mealTypes:['lunch','dinner','snack'], emoji:'🍔' },
  { name:'Burger (Chicken)', category:'snack', cuisineType:'international', servingSize:220, servingUnit:'g', servingLabel:'1 burger (220g)', calories:450, protein:22, carbs:45, fat:20, fiber:3, sugar:5, sodium:850, tags:['non-veg'], mealTypes:['lunch','dinner','snack'], emoji:'🍔' },
  { name:'French Fries', category:'snack', cuisineType:'international', servingSize:100, servingUnit:'g', servingLabel:'Medium fries (100g)', calories:311, protein:3.4, carbs:41, fat:15, fiber:3.8, sugar:0.3, sodium:210, tags:['vegan','vegetarian','fried'], mealTypes:['snack'], emoji:'🍟' },
  { name:'Pasta (Tomato Sauce)', category:'indian_common', cuisineType:'international', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:350, protein:10, carbs:65, fat:5, fiber:4, sugar:6, sodium:400, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍝' },
  { name:'Pasta (White Sauce)', category:'indian_common', cuisineType:'international', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:450, protein:12, carbs:55, fat:20, fiber:2, sugar:4, sodium:550, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍝' },
  { name:'Fried Rice (Veg)', category:'indian_common', cuisineType:'indo_chinese', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:350, protein:6, carbs:60, fat:10, fiber:3, sugar:2, sodium:650, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Hakka Noodles', category:'indian_common', cuisineType:'indo_chinese', servingSize:250, servingUnit:'g', servingLabel:'1 bowl (250g)', calories:380, protein:8, carbs:65, fat:12, fiber:4, sugar:3, sodium:750, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍜' },
  { name:'Chilli Chicken', category:'snack', cuisineType:'indo_chinese', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:320, protein:25, carbs:20, fat:15, fiber:1, sugar:4, sodium:850, tags:['non-veg'], mealTypes:['snack','dinner'], emoji:'🍗' },
  { name:'Manchurian (Gobi)', category:'snack', cuisineType:'indo_chinese', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:280, protein:4, carbs:40, fat:12, fiber:3, sugar:5, sodium:750, tags:['vegan','vegetarian'], mealTypes:['snack','dinner'], emoji:'🥗' },
  
  // ─── SALADS & HEALTHY ─────────────────────────────────────
  { name:'Green Salad', category:'vegetable', cuisineType:'international', servingSize:150, servingUnit:'g', servingLabel:'1 bowl (150g)', calories:30, protein:2, carbs:5, fat:0.5, fiber:3, sugar:2, sodium:15, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🥗' },
  { name:'Sprouts Salad', category:'vegetable', cuisineType:'indian_common', servingSize:150, servingUnit:'g', servingLabel:'1 bowl (150g)', calories:180, protein:12, carbs:30, fat:2, fiber:8, sugar:4, sodium:100, tags:['vegan','vegetarian','high-protein','high-fiber'], mealTypes:['breakfast','snack'], emoji:'🥗' },
  { name:'Fruit Salad', category:'fruit', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 bowl (200g)', calories:120, protein:1.5, carbs:30, fat:0.5, fiber:4, sugar:22, sodium:5, tags:['vegan','vegetarian','hydrating'], mealTypes:['breakfast','snack'], emoji:'🍓' },
  { name:'Roasted Makhana (Fox Nuts)', category:'snack', cuisineType:'common', servingSize:30, servingUnit:'g', servingLabel:'1 bowl (30g)', calories:110, protein:3, carbs:22, fat:1, fiber:2, sugar:0, sodium:60, tags:['vegan','vegetarian','low-calorie'], mealTypes:['snack'], emoji:'🥣' },
  { name:'Chana Chaat', category:'snack', cuisineType:'north_indian', servingSize:150, servingUnit:'g', servingLabel:'1 bowl (150g)', calories:220, protein:10, carbs:35, fat:5, fiber:9, sugar:3, sodium:350, tags:['vegan','vegetarian','high-fiber'], mealTypes:['snack'], emoji:'🥗' },

  // ─── MORE SWEETS & DESSERTS ───────────────────────────────
  { name:'Kheer / Payasam', category:'snack', cuisineType:'indian_common', servingSize:150, servingUnit:'g', servingLabel:'1 bowl (150g)', calories:250, protein:5, carbs:38, fat:8, fiber:0.5, sugar:25, sodium:40, tags:['vegetarian','sweet'], mealTypes:['snack','dinner'], emoji:'🍚' },
  { name:'Gajar Ka Halwa', category:'snack', cuisineType:'north_indian', servingSize:100, servingUnit:'g', servingLabel:'1 small bowl (100g)', calories:320, protein:5, carbs:40, fat:16, fiber:2, sugar:30, sodium:35, tags:['vegetarian','sweet'], mealTypes:['snack','dinner'], emoji:'🥕' },
  { name:'Barfi', category:'snack', cuisineType:'indian_common', servingSize:40, servingUnit:'g', servingLabel:'1 piece (40g)', calories:160, protein:4, carbs:22, fat:7, fiber:0, sugar:18, sodium:10, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'🟨' },
  { name:'Kaju Katli', category:'snack', cuisineType:'indian_common', servingSize:30, servingUnit:'g', servingLabel:'2 pieces (30g)', calories:140, protein:3, carbs:16, fat:7, fiber:1, sugar:12, sodium:2, tags:['vegan','vegetarian','sweet'], mealTypes:['snack'], emoji:'⬜' },
  { name:'Ice Cream (Vanilla)', category:'snack', cuisineType:'international', servingSize:100, servingUnit:'g', servingLabel:'1 scoop (100g)', calories:207, protein:3.5, carbs:24, fat:11, fiber:0, sugar:21, sodium:80, tags:['vegetarian','sweet'], mealTypes:['snack','dinner'], emoji:'🍦' },
  { name:'Chocolate Bar', category:'snack', cuisineType:'international', servingSize:50, servingUnit:'g', servingLabel:'1 small bar (50g)', calories:265, protein:3, carbs:30, fat:15, fiber:1.5, sugar:26, sodium:40, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'🍫' },

  // ─── KARNATAKA REGIONAL ───────────────────────────────────
  { name:'Uppittu', nameAlt:['upma','uppittu'], category:'south_indian', cuisineType:'karnataka', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:220, protein:5, carbs:38, fat:6, fiber:3, sugar:1, sodium:380, tags:['vegetarian','vegan'], mealTypes:['breakfast','snack'], emoji:'🍽️' },
  { name:'Bajji / Bonda', nameAlt:['bajji','bonda','goli bajji'], category:'snack', cuisineType:'karnataka', servingSize:100, servingUnit:'g', servingLabel:'4 pieces (100g)', calories:260, protein:5, carbs:30, fat:14, fiber:3, sugar:2, sodium:420, tags:['vegetarian','fried','street-food'], mealTypes:['snack'], emoji:'🧆' },
  { name:'Jolada Rotti', nameAlt:['jowar roti','jolada roti'], category:'south_indian', cuisineType:'karnataka', servingSize:60, servingUnit:'g', servingLabel:'1 rotti (60g)', calories:135, protein:4, carbs:26, fat:2, fiber:4, sugar:0.5, sodium:5, tags:['vegan','vegetarian','gluten-free','millet'], mealTypes:['lunch','dinner'], emoji:'🫓' },
  { name:'Ragi Mudde', nameAlt:['ragi ball','raagi mudde'], category:'south_indian', cuisineType:'karnataka', servingSize:150, servingUnit:'g', servingLabel:'1 ball (150g)', calories:180, protein:5, carbs:38, fat:1.5, fiber:6, sugar:0, sodium:5, tags:['vegan','vegetarian','gluten-free','millet','high-fiber'], mealTypes:['lunch','dinner'], emoji:'🟤' },
  { name:'Akki Rotti', nameAlt:['rice roti','akki roti'], category:'south_indian', cuisineType:'karnataka', servingSize:80, servingUnit:'g', servingLabel:'1 rotti (80g)', calories:150, protein:3, carbs:28, fat:3, fiber:2, sugar:0.5, sodium:300, tags:['vegan','vegetarian','gluten-free'], mealTypes:['breakfast','lunch','dinner'], emoji:'🫓' },
  { name:'Benne Dosa', nameAlt:['butter dosa','davangere benne dosa'], category:'south_indian', cuisineType:'karnataka', servingSize:120, servingUnit:'g', servingLabel:'1 dosa (120g)', calories:280, protein:5, carbs:38, fat:12, fiber:1, sugar:1, sodium:350, tags:['vegetarian'], mealTypes:['breakfast','snack'], emoji:'🫓' },
  { name:'Neer Dosa', nameAlt:['neer dose'], category:'south_indian', cuisineType:'karnataka', servingSize:80, servingUnit:'g', servingLabel:'2 pieces (80g)', calories:120, protein:2, carbs:24, fat:1.5, fiber:0.5, sugar:0, sodium:100, tags:['vegan','vegetarian','gluten-free'], mealTypes:['breakfast','dinner'], emoji:'🫓' },
  { name:'Set Dosa', nameAlt:['set dose'], category:'south_indian', cuisineType:'karnataka', servingSize:150, servingUnit:'g', servingLabel:'3 pieces (150g)', calories:250, protein:6, carbs:45, fat:4, fiber:2, sugar:1, sodium:350, tags:['vegetarian','fermented'], mealTypes:['breakfast'], emoji:'🫓' },
  { name:'Mysore Masala Dosa', category:'south_indian', cuisineType:'karnataka', servingSize:220, servingUnit:'g', servingLabel:'1 dosa (220g)', calories:390, protein:8, carbs:55, fat:15, fiber:4, sugar:3, sodium:580, tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Paddu / Gundpongalu', nameAlt:['paddu','appe','gundpongalu','paniyaram'], category:'south_indian', cuisineType:'karnataka', servingSize:100, servingUnit:'g', servingLabel:'6 pieces (100g)', calories:190, protein:5, carbs:32, fat:5, fiber:2, sugar:1, sodium:300, tags:['vegetarian','fermented'], mealTypes:['breakfast','snack'], emoji:'🧆' },
  { name:'Rava Idli', category:'south_indian', cuisineType:'karnataka', servingSize:120, servingUnit:'g', servingLabel:'2 pieces (120g)', calories:175, protein:5, carbs:30, fat:3.5, fiber:2, sugar:1, sodium:380, tags:['vegetarian'], mealTypes:['breakfast','snack'], emoji:'🫓' },
  { name:'Mangalore Buns', nameAlt:['banana buns'], category:'south_indian', cuisineType:'karnataka', servingSize:80, servingUnit:'g', servingLabel:'2 pieces (80g)', calories:220, protein:3.5, carbs:35, fat:8, fiber:1.5, sugar:8, sodium:200, tags:['vegetarian','fried'], mealTypes:['breakfast','snack'], emoji:'🥐' },
  { name:'Gojju Avalakki', nameAlt:['gojju poha','beaten rice gojju'], category:'south_indian', cuisineType:'karnataka', servingSize:150, servingUnit:'g', servingLabel:'1 serving (150g)', calories:210, protein:3, carbs:42, fat:4, fiber:2, sugar:5, sodium:400, tags:['vegetarian','vegan'], mealTypes:['breakfast','snack'], emoji:'🍽️' },
  { name:'Chitranna', nameAlt:['lemon rice karnataka','chitranna rice'], category:'south_indian', cuisineType:'karnataka', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:290, protein:5, carbs:50, fat:7, fiber:2, sugar:1, sodium:320, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Vangi Bath', nameAlt:['brinjal rice','vangi bhath'], category:'south_indian', cuisineType:'karnataka', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:340, protein:6, carbs:55, fat:10, fiber:4, sugar:3, sodium:450, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Puliyogare', nameAlt:['tamarind rice','hulianna'], category:'south_indian', cuisineType:'karnataka', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:310, protein:5, carbs:52, fat:9, fiber:3, sugar:4, sodium:400, tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Huli / Saaru', nameAlt:['sambar karnataka','huli saaru'], category:'south_indian', cuisineType:'karnataka', servingSize:200, servingUnit:'ml', servingLabel:'1 cup (200ml)', calories:95, protein:5, carbs:14, fat:2, fiber:4, sugar:2, sodium:450, tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Kosambari', nameAlt:['moong dal salad','kosambri'], category:'south_indian', cuisineType:'karnataka', servingSize:100, servingUnit:'g', servingLabel:'1 serving (100g)', calories:130, protein:8, carbs:20, fat:2, fiber:5, sugar:2, sodium:200, tags:['vegan','vegetarian','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🥗' },
  { name:'Shenga Chutney', nameAlt:['peanut chutney','groundnut chutney'], category:'south_indian', cuisineType:'karnataka', servingSize:30, servingUnit:'g', servingLabel:'2 tbsp (30g)', calories:80, protein:3, carbs:5, fat:6, fiber:1.5, sugar:1, sodium:250, tags:['vegan','vegetarian'], mealTypes:['breakfast','lunch','dinner'], emoji:'🥜' },
  { name:'Coconut Chutney', nameAlt:['kobbari chutney','tengina chutney'], category:'south_indian', cuisineType:'karnataka', servingSize:30, servingUnit:'g', servingLabel:'2 tbsp (30g)', calories:60, protein:1, carbs:4, fat:5, fiber:2, sugar:2, sodium:200, tags:['vegan','vegetarian'], mealTypes:['breakfast','lunch','dinner'], emoji:'🥥' },
  { name:'Ragi Huri Hittu', nameAlt:['ragi malt','ragi porridge'], category:'beverage', cuisineType:'karnataka', servingSize:250, servingUnit:'ml', servingLabel:'1 glass (250ml)', calories:180, protein:4, carbs:35, fat:2, fiber:5, sugar:8, sodium:20, tags:['vegan','vegetarian','millet','high-fiber'], mealTypes:['breakfast','snack'], emoji:'🥛' },
  { name:'Ragi Dosa', nameAlt:['raagi dose'], category:'south_indian', cuisineType:'karnataka', servingSize:100, servingUnit:'g', servingLabel:'1 dosa (100g)', calories:155, protein:4, carbs:30, fat:2.5, fiber:4, sugar:0.5, sodium:280, tags:['vegan','vegetarian','gluten-free','millet'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Mysore Pak', category:'snack', cuisineType:'karnataka', servingSize:40, servingUnit:'g', servingLabel:'1 piece (40g)', calories:230, protein:3, carbs:22, fat:15, fiber:1, sugar:16, sodium:5, tags:['vegetarian','sweet'], mealTypes:['snack'], emoji:'🟨' },
  { name:'Chiroti', nameAlt:['chiroti sweet'], category:'snack', cuisineType:'karnataka', servingSize:50, servingUnit:'g', servingLabel:'1 piece (50g)', calories:210, protein:2, carbs:28, fat:10, fiber:0.5, sugar:14, sodium:10, tags:['vegetarian','sweet','fried'], mealTypes:['snack'], emoji:'🥐' },
  { name:'Obbattu / Holige', nameAlt:['holige','bele obbattu','puran poli karnataka'], category:'snack', cuisineType:'karnataka', servingSize:100, servingUnit:'g', servingLabel:'1 piece (100g)', calories:280, protein:6, carbs:52, fat:5, fiber:4, sugar:20, sodium:15, tags:['vegetarian','sweet'], mealTypes:['snack','lunch'], emoji:'🫓' },
  { name:'Kesari Bath', nameAlt:['rava kesari','sheera'], category:'snack', cuisineType:'karnataka', servingSize:100, servingUnit:'g', servingLabel:'1 serving (100g)', calories:300, protein:3, carbs:45, fat:12, fiber:0.5, sugar:25, sodium:20, tags:['vegetarian','sweet'], mealTypes:['breakfast','snack'], emoji:'🟧' },
  { name:'Karadantu', nameAlt:['karadantu sweet','dry fruit chikki'], category:'snack', cuisineType:'karnataka', servingSize:30, servingUnit:'g', servingLabel:'1 piece (30g)', calories:130, protein:3, carbs:18, fat:6, fiber:2, sugar:10, sodium:5, tags:['vegetarian','sweet','dry-fruit'], mealTypes:['snack'], emoji:'🍬' },
  { name:'Uddina Vada', nameAlt:['urad dal vada','medu vada karnataka'], category:'south_indian', cuisineType:'karnataka', servingSize:80, servingUnit:'g', servingLabel:'1 piece (80g)', calories:225, protein:7, carbs:26, fat:10, fiber:3, sugar:1, sodium:380, tags:['vegetarian','fried','fermented'], mealTypes:['breakfast','snack'], emoji:'🍩' },
  { name:'Bisi Bele Hulianna', nameAlt:['bisi bele bath karnataka'], category:'south_indian', cuisineType:'karnataka', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)', calories:370, protein:10, carbs:55, fat:11, fiber:6, sugar:3, sodium:520, tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Khara Bath', nameAlt:['rava bath','masala bath'], category:'south_indian', cuisineType:'karnataka', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)', calories:260, protein:5, carbs:38, fat:9, fiber:2, sugar:1, sodium:400, tags:['vegetarian'], mealTypes:['breakfast','snack'], emoji:'🍽️' }
];

module.exports = async function seedFoods() {
  try {
    // Upsert each food by name (so re-running never duplicates, but updates exist)
    for (const f of FOODS) {
      await Food.updateOne({ name: f.name }, { $setOnInsert: f }, { upsert: true });
    }
    const final = await Food.countDocuments();
    console.log(`[Seed] Food DB seeded — ${final} items total 🌱`);
  } catch (err) {
    console.error('[Seed] seedFoods error:', err.message);
  }
};
