const Food = require('../models/Food');

const FOODS = [
  // ─── FRUITS ──────────────────────────────────────────────
  { name:'Banana', nameAlt:['kela'], category:'fruit', cuisineType:'common', servingSize:120, servingUnit:'g', servingLabel:'1 medium (120g)',
    calories:107, protein:1.3, carbs:27, fat:0.4, fiber:3.1, sugar:14, sodium:1,
    tags:['vegan','vegetarian','high-carb'], mealTypes:['breakfast','snack'], emoji:'🍌' },
  { name:'Apple', nameAlt:['seb'], category:'fruit', cuisineType:'common', servingSize:182, servingUnit:'g', servingLabel:'1 medium (182g)',
    calories:95, protein:0.5, carbs:25, fat:0.3, fiber:4.4, sugar:19, sodium:2,
    tags:['vegan','vegetarian','low-fat'], mealTypes:['breakfast','snack'], emoji:'🍎' },
  { name:'Mango', nameAlt:['aam'], category:'fruit', cuisineType:'common', servingSize:165, servingUnit:'g', servingLabel:'1 cup sliced (165g)',
    calories:99, protein:1.4, carbs:25, fat:0.6, fiber:2.6, sugar:22, sodium:2,
    tags:['vegan','vegetarian'], mealTypes:['breakfast','snack'], emoji:'🥭' },
  { name:'Orange', nameAlt:['santra','narangi'], category:'fruit', cuisineType:'common', servingSize:131, servingUnit:'g', servingLabel:'1 medium (131g)',
    calories:62, protein:1.2, carbs:15, fat:0.2, fiber:3.1, sugar:12, sodium:0,
    tags:['vegan','vegetarian','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🍊' },
  { name:'Grapes', nameAlt:['angoor'], category:'fruit', cuisineType:'common', servingSize:150, servingUnit:'g', servingLabel:'1 cup (150g)',
    calories:104, protein:1.1, carbs:27, fat:0.2, fiber:1.4, sugar:23, sodium:3,
    tags:['vegan','vegetarian'], mealTypes:['snack'], emoji:'🍇' },
  { name:'Watermelon', nameAlt:['tarbooz'], category:'fruit', cuisineType:'common', servingSize:280, servingUnit:'g', servingLabel:'2 cups (280g)',
    calories:85, protein:1.7, carbs:21, fat:0.4, fiber:1.1, sugar:17, sodium:3,
    tags:['vegan','vegetarian','low-calorie','hydrating'], mealTypes:['snack'], emoji:'🍉' },
  { name:'Papaya', nameAlt:['papita'], category:'fruit', cuisineType:'common', servingSize:145, servingUnit:'g', servingLabel:'1 cup (145g)',
    calories:62, protein:0.7, carbs:16, fat:0.4, fiber:2.5, sugar:11, sodium:12,
    tags:['vegan','vegetarian','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🍈' },

  // ─── VEGETABLES ──────────────────────────────────────────
  { name:'Carrot', nameAlt:['gajar'], category:'vegetable', cuisineType:'common', servingSize:128, servingUnit:'g', servingLabel:'1 cup chopped (128g)',
    calories:52, protein:1.2, carbs:12, fat:0.3, fiber:3.6, sugar:6, sodium:88,
    tags:['vegan','vegetarian','low-calorie','high-fiber'], mealTypes:['lunch','dinner','snack'], emoji:'🥕' },
  { name:'Broccoli', category:'vegetable', cuisineType:'international', servingSize:91, servingUnit:'g', servingLabel:'1 cup (91g)',
    calories:31, protein:2.6, carbs:6, fat:0.3, fiber:2.4, sugar:1.5, sodium:30,
    tags:['vegan','vegetarian','low-calorie','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🥦' },
  { name:'Spinach', nameAlt:['palak'], category:'vegetable', cuisineType:'common', servingSize:30, servingUnit:'g', servingLabel:'1 cup raw (30g)',
    calories:7, protein:0.9, carbs:1.1, fat:0.1, fiber:0.7, sugar:0.1, sodium:24,
    tags:['vegan','vegetarian','low-calorie','iron-rich'], mealTypes:['lunch','dinner'], emoji:'🥬' },
  { name:'Potato', nameAlt:['aloo'], category:'vegetable', cuisineType:'common', servingSize:150, servingUnit:'g', servingLabel:'1 medium (150g)',
    calories:130, protein:3, carbs:30, fat:0.2, fiber:2.4, sugar:1.3, sodium:10,
    tags:['vegan','vegetarian'], mealTypes:['breakfast','lunch','dinner'], emoji:'🥔' },
  { name:'Tomato', nameAlt:['tamatar'], category:'vegetable', cuisineType:'common', servingSize:123, servingUnit:'g', servingLabel:'1 medium (123g)',
    calories:22, protein:1.1, carbs:4.8, fat:0.2, fiber:1.5, sugar:3.2, sodium:6,
    tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🍅' },
  { name:'Onion', nameAlt:['pyaz'], category:'vegetable', cuisineType:'common', servingSize:110, servingUnit:'g', servingLabel:'1 medium (110g)',
    calories:44, protein:1.2, carbs:10, fat:0.1, fiber:1.9, sugar:4.7, sodium:5,
    tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🧅' },

  // ─── SOUTH INDIAN ────────────────────────────────────────
  { name:'Idli', category:'south_indian', cuisineType:'south_indian', servingSize:120, servingUnit:'g', servingLabel:'2 pieces (120g)',
    calories:148, protein:4.8, carbs:30, fat:0.6, fiber:1.2, sugar:0.5, sodium:320,
    tags:['vegetarian','low-fat','fermented'], mealTypes:['breakfast','snack'], emoji:'🫓' },
  { name:'Plain Dosa', nameAlt:['dosa'], category:'south_indian', cuisineType:'south_indian', servingSize:100, servingUnit:'g', servingLabel:'1 dosa (100g)',
    calories:168, protein:4, carbs:35, fat:1.5, fiber:1.5, sugar:0.8, sodium:300,
    tags:['vegetarian','fermented'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Masala Dosa', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 dosa (200g)',
    calories:340, protein:7, carbs:56, fat:9, fiber:3, sugar:2, sodium:520,
    tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🫓' },
  { name:'Sambar', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'ml', servingLabel:'1 cup (200ml)',
    calories:102, protein:5.2, carbs:16, fat:2.4, fiber:4, sugar:3, sodium:480,
    tags:['vegan','vegetarian','high-fiber'], mealTypes:['breakfast','lunch','dinner'], emoji:'🍲' },
  { name:'Pongal', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)',
    calories:280, protein:7, carbs:48, fat:7, fiber:2, sugar:1, sodium:350,
    tags:['vegetarian'], mealTypes:['breakfast'], emoji:'🍚' },
  { name:'Uttapam', category:'south_indian', cuisineType:'south_indian', servingSize:150, servingUnit:'g', servingLabel:'1 piece (150g)',
    calories:218, protein:6, carbs:38, fat:4, fiber:2, sugar:2, sodium:380,
    tags:['vegetarian'], mealTypes:['breakfast','snack'], emoji:'🥞' },
  { name:'Curd Rice', nameAlt:['thayir sadam'], category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)',
    calories:240, protein:7, carbs:44, fat:3.5, fiber:0.5, sugar:3, sodium:280,
    tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Rasam', category:'south_indian', cuisineType:'south_indian', servingSize:200, servingUnit:'ml', servingLabel:'1 cup (200ml)',
    calories:55, protein:1.5, carbs:10, fat:1, fiber:1.2, sugar:1.5, sodium:440,
    tags:['vegan','vegetarian','low-calorie'], mealTypes:['lunch','dinner'], emoji:'🍵' },

  // ─── NORTH INDIAN ────────────────────────────────────────
  { name:'Roti / Chapati', nameAlt:['chapati','roti','phulka'], category:'north_indian', cuisineType:'north_indian', servingSize:40, servingUnit:'g', servingLabel:'1 roti (40g)',
    calories:104, protein:3.5, carbs:19, fat:2, fiber:2.5, sugar:0.4, sodium:130,
    tags:['vegetarian','whole-wheat'], mealTypes:['breakfast','lunch','dinner'], emoji:'🫓' },
  { name:'Naan', category:'north_indian', cuisineType:'north_indian', servingSize:90, servingUnit:'g', servingLabel:'1 piece (90g)',
    calories:262, protein:8.5, carbs:45, fat:5.5, fiber:1.8, sugar:3, sodium:520,
    tags:['vegetarian'], mealTypes:['lunch','dinner'], emoji:'🫓' },
  { name:'Paratha', nameAlt:['stuffed paratha'], category:'north_indian', cuisineType:'north_indian', servingSize:100, servingUnit:'g', servingLabel:'1 paratha (100g)',
    calories:300, protein:6, carbs:42, fat:11, fiber:3, sugar:1, sodium:450,
    tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🥙' },
  { name:'Paneer Butter Masala', nameAlt:['paneer makhani'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)',
    calories:430, protein:20, carbs:18, fat:32, fiber:3, sugar:8, sodium:680,
    tags:['vegetarian','high-protein','high-fat'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Dal Makhani', nameAlt:['dal makhni'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)',
    calories:310, protein:14, carbs:38, fat:10, fiber:9, sugar:4, sodium:580,
    tags:['vegetarian','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Rajma', nameAlt:['kidney beans curry'], category:'north_indian', cuisineType:'north_indian', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)',
    calories:290, protein:16, carbs:44, fat:5, fiber:12, sugar:3, sodium:480,
    tags:['vegan','vegetarian','high-fiber','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍲' },
  { name:'Chole Bhature', nameAlt:['chhole bhature'], category:'north_indian', cuisineType:'north_indian', servingSize:300, servingUnit:'g', servingLabel:'1 plate (300g)',
    calories:580, protein:16, carbs:78, fat:22, fiber:10, sugar:5, sodium:820,
    tags:['vegetarian'], mealTypes:['breakfast','lunch'], emoji:'🍽️' },

  // ─── INDIAN COMMON ───────────────────────────────────────
  { name:'Steamed Rice', nameAlt:['white rice','boiled rice','chawal'], category:'indian_common', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 cup cooked (200g)',
    calories:258, protein:5.3, carbs:56, fat:0.5, fiber:0.6, sugar:0, sodium:4,
    tags:['vegan','vegetarian'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Ghee', category:'indian_common', cuisineType:'common', servingSize:15, servingUnit:'g', servingLabel:'1 tbsp (15g)',
    calories:135, protein:0, carbs:0, fat:15, fiber:0, sugar:0, sodium:0,
    tags:['vegetarian','high-fat'], mealTypes:['breakfast','lunch','dinner'], emoji:'🧈' },
  { name:'Curd / Yogurt', nameAlt:['dahi','yogurt'], category:'dairy', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 cup (200g)',
    calories:118, protein:8, carbs:9, fat:4.6, fiber:0, sugar:7, sodium:115,
    tags:['vegetarian','probiotic','calcium-rich'], mealTypes:['breakfast','lunch','dinner','snack'], emoji:'🥛' },
  { name:'Milk', nameAlt:['dudh'], category:'dairy', cuisineType:'common', servingSize:240, servingUnit:'ml', servingLabel:'1 glass (240ml)',
    calories:149, protein:8, carbs:12, fat:8, fiber:0, sugar:12, sodium:105,
    tags:['vegetarian','calcium-rich'], mealTypes:['breakfast','snack'], emoji:'🥛' },
  { name:'Egg (Boiled)', nameAlt:['anda','egg'], category:'protein', cuisineType:'common', servingSize:50, servingUnit:'g', servingLabel:'1 large (50g)',
    calories:78, protein:6.3, carbs:0.6, fat:5.3, fiber:0, sugar:0.6, sodium:62,
    tags:['high-protein','low-carb'], mealTypes:['breakfast','snack'], emoji:'🥚' },
  { name:'Chicken Curry', nameAlt:['murgh curry'], category:'indian_common', cuisineType:'common', servingSize:250, servingUnit:'g', servingLabel:'1 serving (250g)',
    calories:395, protein:32, carbs:12, fat:24, fiber:2, sugar:4, sodium:690,
    tags:['high-protein','non-veg'], mealTypes:['lunch','dinner'], emoji:'🍗' },
  { name:'Biryani (Chicken)', nameAlt:['chicken biryani'], category:'indian_common', cuisineType:'common', servingSize:350, servingUnit:'g', servingLabel:'1 plate (350g)',
    calories:520, protein:28, carbs:68, fat:16, fiber:3, sugar:4, sodium:780,
    tags:['non-veg','high-protein'], mealTypes:['lunch','dinner'], emoji:'🍛' },
  { name:'Upma', category:'indian_common', cuisineType:'south_indian', servingSize:200, servingUnit:'g', servingLabel:'1 serving (200g)',
    calories:202, protein:5, carbs:36, fat:5, fiber:2.5, sugar:1, sodium:360,
    tags:['vegetarian','vegan'], mealTypes:['breakfast','snack'], emoji:'🍽️' },
  { name:'Poha', category:'indian_common', cuisineType:'common', servingSize:200, servingUnit:'g', servingLabel:'1 plate (200g)',
    calories:250, protein:4.5, carbs:50, fat:4, fiber:2, sugar:2, sodium:320,
    tags:['vegetarian','vegan'], mealTypes:['breakfast','snack'], emoji:'🍽️' },

  // ─── GYM / PROTEIN FOODS ─────────────────────────────────
  { name:'Chicken Breast (Grilled)', nameAlt:['grilled chicken'], category:'gym', cuisineType:'international', servingSize:150, servingUnit:'g', servingLabel:'1 fillet (150g)',
    calories:247, protein:46, carbs:0, fat:5.3, fiber:0, sugar:0, sodium:129,
    tags:['high-protein','low-carb','low-fat','non-veg'], mealTypes:['lunch','dinner'], emoji:'🍗' },
  { name:'Whey Protein Shake', nameAlt:['protein shake','whey'], category:'gym', cuisineType:'international', servingSize:30, servingUnit:'g', servingLabel:'1 scoop (30g)',
    calories:120, protein:24, carbs:3, fat:1.5, fiber:0, sugar:2, sodium:130,
    tags:['high-protein','low-carb','gym'], mealTypes:['breakfast','snack'], emoji:'💪' },
  { name:'Oats', nameAlt:['oatmeal','rolled oats'], category:'grain', cuisineType:'international', servingSize:80, servingUnit:'g', servingLabel:'1 cup dry (80g)',
    calories:296, protein:10, carbs:53, fat:5.2, fiber:8, sugar:1, sodium:5,
    tags:['vegan','vegetarian','high-fiber','gym'], mealTypes:['breakfast'], emoji:'🥣' },
  { name:'Brown Rice', category:'grain', cuisineType:'international', servingSize:195, servingUnit:'g', servingLabel:'1 cup cooked (195g)',
    calories:216, protein:5, carbs:45, fat:1.8, fiber:3.5, sugar:0.7, sodium:10,
    tags:['vegan','vegetarian','high-fiber','gym'], mealTypes:['lunch','dinner'], emoji:'🍚' },
  { name:'Greek Yogurt', nameAlt:['greek curd'], category:'dairy', cuisineType:'international', servingSize:200, servingUnit:'g', servingLabel:'1 cup (200g)',
    calories:130, protein:17, carbs:7, fat:3.5, fiber:0, sugar:6, sodium:95,
    tags:['vegetarian','high-protein','gym','probiotic'], mealTypes:['breakfast','snack'], emoji:'🥛' },
  { name:'Almonds', nameAlt:['badam'], category:'snack', cuisineType:'common', servingSize:28, servingUnit:'g', servingLabel:'1 oz / ~23 nuts (28g)',
    calories:164, protein:6, carbs:6, fat:14, fiber:3.5, sugar:1.2, sodium:1,
    tags:['vegan','vegetarian','high-fat','gym','keto-friendly'], mealTypes:['snack'], emoji:'🌰' },
  { name:'Peanut Butter', nameAlt:['peanut butter','moongfali butter'], category:'gym', cuisineType:'international', servingSize:32, servingUnit:'g', servingLabel:'2 tbsp (32g)',
    calories:188, protein:8, carbs:7, fat:16, fiber:1.9, sugar:3, sodium:152,
    tags:['vegetarian','high-protein','high-fat','gym'], mealTypes:['breakfast','snack'], emoji:'🥜' },
  { name:'Quinoa', category:'grain', cuisineType:'international', servingSize:185, servingUnit:'g', servingLabel:'1 cup cooked (185g)',
    calories:222, protein:8, carbs:39, fat:3.5, fiber:5, sugar:1.6, sodium:13,
    tags:['vegan','vegetarian','high-protein','gym','gluten-free'], mealTypes:['lunch','dinner'], emoji:'🌾' },
  { name:'Tuna (Canned)', nameAlt:['canned tuna'], category:'gym', cuisineType:'international', servingSize:100, servingUnit:'g', servingLabel:'1 small can (100g)',
    calories:116, protein:25, carbs:0, fat:1, fiber:0, sugar:0, sodium:333,
    tags:['high-protein','low-carb','low-fat','non-veg','gym'], mealTypes:['lunch','dinner'], emoji:'🐟' },

  // ─── SNACKS & BEVERAGES ──────────────────────────────────
  { name:'Samosa', category:'snack', cuisineType:'north_indian', servingSize:100, servingUnit:'g', servingLabel:'1 piece (100g)',
    calories:262, protein:5, carbs:30, fat:14, fiber:2.5, sugar:2, sodium:420,
    tags:['vegetarian'], mealTypes:['snack'], emoji:'🥟' },
  { name:'Black Coffee', nameAlt:['coffee','black coffee'], category:'beverage', cuisineType:'international', servingSize:240, servingUnit:'ml', servingLabel:'1 cup (240ml)',
    calories:5, protein:0.3, carbs:0, fat:0, fiber:0, sugar:0, sodium:7,
    tags:['vegan','low-calorie','gym'], mealTypes:['breakfast','snack'], emoji:'☕' },
  { name:'Green Tea', nameAlt:['herbal tea'], category:'beverage', cuisineType:'international', servingSize:240, servingUnit:'ml', servingLabel:'1 cup (240ml)',
    calories:3, protein:0, carbs:0, fat:0, fiber:0, sugar:0, sodium:7,
    tags:['vegan','low-calorie'], mealTypes:['breakfast','snack'], emoji:'🍵' },
  { name:'Banana Milkshake', nameAlt:['milkshake','banana shake'], category:'beverage', cuisineType:'common', servingSize:300, servingUnit:'ml', servingLabel:'1 glass (300ml)',
    calories:260, protein:7, carbs:45, fat:6, fiber:2, sugar:36, sodium:100,
    tags:['vegetarian','gym'], mealTypes:['breakfast','snack'], emoji:'🥤' },
  { name:'Paneer (Cottage Cheese)', nameAlt:['paneer','cottage cheese'], category:'dairy', cuisineType:'common', servingSize:100, servingUnit:'g', servingLabel:'100g',
    calories:265, protein:18, carbs:3, fat:20, fiber:0, sugar:2, sodium:120,
    tags:['vegetarian','high-protein','gym','keto-friendly'], mealTypes:['breakfast','lunch','dinner','snack'], emoji:'🧀' },
  { name:'Salmon (Grilled)', nameAlt:['salmon','fish'], category:'gym', cuisineType:'international', servingSize:150, servingUnit:'g', servingLabel:'1 fillet (150g)',
    calories:280, protein:39, carbs:0, fat:13, fiber:0, sugar:0, sodium:100,
    tags:['high-protein','low-carb','non-veg','gym','omega-3'], mealTypes:['lunch','dinner'], emoji:'🐟' },
];

module.exports = async function seedFoods() {
  try {
    const count = await Food.countDocuments();
    if (count >= FOODS.length) {
      console.log(`[Seed] Food DB already seeded (${count} items) ✅`);
      return;
    }
    // Upsert each food by name (so re-running never duplicates)
    for (const f of FOODS) {
      await Food.updateOne({ name: f.name }, { $setOnInsert: f }, { upsert: true });
    }
    const final = await Food.countDocuments();
    console.log(`[Seed] Food DB seeded — ${final} items total 🌱`);
  } catch (err) {
    console.error('[Seed] seedFoods error:', err.message);
  }
};
